version: '3.8'

services:
  mysql:
    container_name: eventosDb
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nest-events
      PORT: 3307

  # postgres:
  #   image: postgres:13.1
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   ports:
  #     - 5432:5432

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
