services:
  eventosDb:
    container_name: eventosDb
    image: mysql:8.0.23
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env.dev
